version: '3.2'
services:
  wordpress:
    image: wordpress:php7.1-apache
    links:
      - db:mysql
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data/code:/code
      - ./data/html:/var/www/html
    environment:
      DB_NAME: wordpress
      DB_PASS: root
  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
volumes:
  data:
